### ISSUE TITLE
Code Packaging

### ISSUE THREAD

**Issue by dauofl** [Sprollie/VinMartAuth#30]
Kiên ơi please sắp xếp lại cái đống code của cậu :))) ý là chia lại package cho fragment, activity, adapter
If you feel rảnh you can chia package luôn cho feature của các bạn nhé hihi thank you

**Comment by Sprollie** [comment]
@dauofl issue giải quyết xong chưa

**Comment by Sprollie** [comment]
xong rồi thì tự đóng lại nhé @dauofl

**Comment by Tamkien** [comment]
Từ từ hẵng đóng. Có lẽ phải chia cả layout nữa.

**Comment by Tamkien** [comment]
Không chia layout nữa hay sao mà đã close rồi? Nhiều layouts lắm đấy

**Comment by Sprollie** [comment]
chia layout cứ chia đi liên quan gì đấy issue đâu ông

**Comment by Sprollie** [comment]
mà cái vấn đề ở đây là project structure chứ cũng k phải code packaging

**Comment by Tamkien** [comment]
Okay 👍
