### ISSUE TITLE
Remove your Google API information

### ISSUE THREAD

**Issue by dttad** [Sprollie/VinMartAuth#55]
For security purpose 💯 
[](https://github.com/Sprollie/VinMartAuth/blob/main/app/google-services.json)

**Comment by TuesdayTaco71** [comment]
ai đây?

**Comment by dttad** [comment]
tôi thấy ông để lộ cái API bên Google service nên tôi create issue vậy thôi. Còn ông thấy phiền có thể để t xóa issue này :)

**Comment by TuesdayTaco71** [comment]
à tôi cũng không biết. Nếu vậy thì xin cảm ơn

**Comment by dttad** [comment]
ừm. Vì trước t cũng để lộ, và dính cái bill sml bên Google service :)

**Comment by minh-hd** [comment]
Thanks for your information. Repo để làm bài tập thôi mà :v
